version: "3.3"  # optional since v1.27.0
services:
  depthai:
    #image: luxonis/depthai-library:v2.14.0.0
    image: luxonis/depthai-library:multiarch
    privileged: true
    volumes:
      - .:/code
    devices: 
      - "/dev/bus/usb:/dev/bus/usb"
    device_cgroup_rules:
      - "c 189:* rmw"
