---
name: deploy-yak-prime
run-name: Deploying to yak-prime
on:
  push:
    branches:
      - 'main'
      - 'rhettg-*'
jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Tailscale
      uses: tailscale/github-action@v1
      with:
        authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '^1.19.2'
        cache: true
        cache-dependency-path: yakapi/go.sum
    - run: cd yakapi && go build -o bin/yakapi.${{ github.sha }} .
    - run: scp -o 'StrictHostKeyChecking no' yakapi/bin/* github@yak-prime:/var/yakapi
    #-run: tailscale file cp yakapi/bin/yakapi.* yak-prime:
    - run: curl -v http://yak-prime/v1